services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Importer\:
        resource: '../../src/Importer/*'

    _instanceof:
        App\Importer\DataMapper\MapperItemInterface:
            tags: ['app.importer.data_mapper.restricted']

    App\Importer\DataMapper\ChainMapper:
        arguments:
            $mappers: !tagged_iterator app.importer.data_mapper.restricted
